name = "utilsbr"
version = "0.5.0"

description = "A simple brazillian documents such as CPF and CNPJ utilities library"
licences = ["Apache-2.0"]
repository = { type = "github", user = "malvfr", repo = "utilsbr" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
